/* 由 build-data.mjs 生成，不要手改。跑 `node packages/app/poster/build-data.mjs` 重出。 */
window.SB_POSTER = {
  "generatedAt": "2026-09-13T11:20:37.938Z",
  "source": {
    "parts": "assets/parts/parts.json",
    "curation": "assets/parts/curation.json",
    "partsGeneratedAt": "2026-09-13T09:11:19.182Z",
    "partsVersion": 1
  },
  "counts": {
    "entries": 29,
    "parts": 208,
    "partsRejected": 11,
    "partsLive": 204,
    "partsReal": 30,
    "slots": 10,
    "boneKeys": 18,
    "materials": 9,
    "plans": 9,
    "triangles": 613597,
    "entriesWithAnchor": 22,
    "vacancies": 4,
    "fullyBorrowed": 1
  },
  "bySlot": {
    "clavicle": 11,
    "foot": 27,
    "foreArm": 11,
    "hand": 11,
    "head": 27,
    "joint": 27,
    "shin": 27,
    "spine": 29,
    "thigh": 11,
    "upperArm": 27
  },
  "byPlan": {
    "rig": 11,
    "quadruped": 4,
    "inverted": 1,
    "mass": 3,
    "stub": 3,
    "radial": 2,
    "column": 2,
    "swarm": 1,
    "towering": 2
  },
  "byKind": {
    "archetype": 18,
    "guest": 1,
    "character": 10
  },
  "tier": 2,
  "totalBodies": 1446403,
  "entries": [
    {
      "id": "porcelain",
      "kind": "archetype",
      "name": "瓷",
      "nameEn": "Porcelain",
      "tagline": "一个被理想化过的你",
      "taglineEn": "An idealised version of you",
      "plan": "rig",
      "coverage": "full",
      "base": null,
      "axes": {
        "humanLike": 0.95,
        "lifeLike": 0.35
      },
      "palette": [
        "matte.bone",
        "matte.ash",
        "ceramic.pearl"
      ],
      "ownParts": 20,
      "ownRejected": 0,
      "fullyBorrowed": false,
      "bodies": 262144,
      "perSlot": {
        "spine": 2,
        "neck": 2,
        "head": 2,
        "clavicleL": 2,
        "clavicleR": 2,
        "upperArmL": 2,
        "upperArmR": 2,
        "foreArmL": 2,
        "foreArmR": 2,
        "handL": 2,
        "handR": 2,
        "thighL": 2,
        "thighR": 2,
        "shinL": 2,
        "shinR": 2,
        "footL": 2,
        "footR": 2,
        "joint": 2
      },
      "anchor": true
    },
    {
      "id": "industrial",
      "kind": "archetype",
      "name": "工业",
      "nameEn": "Industrial",
      "tagline": "它是来上班的，不是来陪你的",
      "taglineEn": "It came to work, not to keep you company",
      "plan": "rig",
      "coverage": "full",
      "base": null,
      "axes": {
        "humanLike": 0.9,
        "lifeLike": 0.2
      },
      "palette": [
        "metal.graphite",
        "matte.ash",
        "metal.brass"
      ],
      "ownParts": 20,
      "ownRejected": 0,
      "fullyBorrowed": false,
      "bodies": 262144,
      "perSlot": {
        "spine": 2,
        "neck": 2,
        "head": 2,
        "clavicleL": 2,
        "clavicleR": 2,
        "upperArmL": 2,
        "upperArmR": 2,
        "foreArmL": 2,
        "foreArmR": 2,
        "handL": 2,
        "handR": 2,
        "thighL": 2,
        "thighR": 2,
        "shinL": 2,
        "shinR": 2,
        "footL": 2,
        "footR": 2,
        "joint": 2
      },
      "anchor": true
    },
    {
      "id": "patrol",
      "kind": "archetype",
      "name": "巡逻",
      "nameEn": "Patrol",
      "tagline": "一个不该直立的东西直立了",
      "taglineEn": "Something that should not stand, standing",
      "plan": "quadruped",
      "coverage": "full",
      "base": null,
      "axes": {
        "humanLike": 0.45,
        "lifeLike": 0.45
      },
      "palette": [
        "paint.hazard",
        "metal.graphite",
        "glow.signal"
      ],
      "ownParts": 10,
      "ownRejected": 0,
      "fullyBorrowed": false,
      "bodies": 1,
      "perSlot": {
        "spine": 1,
        "neck": 1,
        "head": 1,
        "clavicleL": 1,
        "clavicleR": 1,
        "upperArmL": 1,
        "upperArmR": 1,
        "foreArmL": 1,
        "foreArmR": 1,
        "handL": 1,
        "handR": 1,
        "thighL": 1,
        "thighR": 1,
        "shinL": 1,
        "shinR": 1,
        "footL": 1,
        "footR": 1,
        "joint": 1
      },
      "anchor": true
    },
    {
      "id": "xeno",
      "kind": "archetype",
      "name": "异形",
      "nameEn": "Xeno",
      "tagline": "它在模仿你，但模仿错了",
      "taglineEn": "It is imitating you, and getting it wrong",
      "plan": "inverted",
      "coverage": "full",
      "base": null,
      "axes": {
        "humanLike": 0.7,
        "lifeLike": 0.75
      },
      "palette": [
        "chitin.deep",
        "metal.graphite",
        "glow.signal"
      ],
      "ownParts": 20,
      "ownRejected": 0,
      "fullyBorrowed": false,
      "bodies": 262144,
      "perSlot": {
        "spine": 2,
        "neck": 2,
        "head": 2,
        "clavicleL": 2,
        "clavicleR": 2,
        "upperArmL": 2,
        "upperArmR": 2,
        "foreArmL": 2,
        "foreArmR": 2,
        "handL": 2,
        "handR": 2,
        "thighL": 2,
        "thighR": 2,
        "shinL": 2,
        "shinR": 2,
        "footL": 2,
        "footR": 2,
        "joint": 2
      },
      "anchor": true
    },
    {
      "id": "coral",
      "kind": "archetype",
      "name": "珊瑚",
      "nameEn": "Coral",
      "tagline": "既不是人，也不是机器",
      "taglineEn": "Neither human nor machine",
      "plan": "mass",
      "coverage": "full",
      "base": null,
      "axes": {
        "humanLike": 0.35,
        "lifeLike": 0.7
      },
      "palette": [
        "matte.bone",
        "chitin.deep",
        "metal.brass"
      ],
      "ownParts": 20,
      "ownRejected": 0,
      "fullyBorrowed": false,
      "bodies": 262144,
      "perSlot": {
        "spine": 2,
        "neck": 2,
        "head": 2,
        "clavicleL": 2,
        "clavicleR": 2,
        "upperArmL": 2,
        "upperArmR": 2,
        "foreArmL": 2,
        "foreArmR": 2,
        "handL": 2,
        "handR": 2,
        "thighL": 2,
        "thighR": 2,
        "shinL": 2,
        "shinR": 2,
        "footL": 2,
        "footR": 2,
        "joint": 2
      },
      "anchor": true
    },
    {
      "id": "athlete",
      "kind": "archetype",
      "name": "运动员",
      "nameEn": "Athlete",
      "tagline": "身体是人，运动不是",
      "taglineEn": "The body is human. The motion is not.",
      "plan": "rig",
      "coverage": "light",
      "base": "porcelain",
      "axes": {
        "humanLike": 0.85,
        "lifeLike": 0.5
      },
      "palette": [
        "metal.graphite",
        "matte.ash",
        "glow.signal"
      ],
      "ownParts": 6,
      "ownRejected": 0,
      "fullyBorrowed": false,
      "bodies": 256,
      "perSlot": {
        "spine": 1,
        "neck": 1,
        "head": 1,
        "clavicleL": 2,
        "clavicleR": 2,
        "upperArmL": 1,
        "upperArmR": 1,
        "foreArmL": 2,
        "foreArmR": 2,
        "handL": 2,
        "handR": 2,
        "thighL": 2,
        "thighR": 2,
        "shinL": 1,
        "shinR": 1,
        "footL": 1,
        "footR": 1,
        "joint": 1
      },
      "anchor": true
    },
    {
      "id": "softwear",
      "kind": "archetype",
      "name": "穿衣的",
      "nameEn": "Softwear",
      "tagline": "一个住在家里的陌生室友",
      "taglineEn": "A stranger who lives in your house",
      "plan": "rig",
      "coverage": "light",
      "base": "porcelain",
      "axes": {
        "humanLike": 0.9,
        "lifeLike": 0.55
      },
      "palette": [
        "matte.bone",
        "paint.hazard",
        "matte.ash"
      ],
      "ownParts": 6,
      "ownRejected": 1,
      "fullyBorrowed": false,
      "bodies": 512,
      "perSlot": {
        "spine": 1,
        "neck": 1,
        "head": 2,
        "clavicleL": 2,
        "clavicleR": 2,
        "upperArmL": 1,
        "upperArmR": 1,
        "foreArmL": 2,
        "foreArmR": 2,
        "handL": 2,
        "handR": 2,
        "thighL": 2,
        "thighR": 2,
        "shinL": 1,
        "shinR": 1,
        "footL": 1,
        "footR": 1,
        "joint": 1
      },
      "anchor": true
    },
    {
      "id": "compact",
      "kind": "archetype",
      "name": "小人",
      "nameEn": "Compact",
      "tagline": "人形，但只有一米三",
      "taglineEn": "Human-shaped, but only 130 cm",
      "plan": "stub",
      "coverage": "light",
      "base": "porcelain",
      "axes": {
        "humanLike": 0.9,
        "lifeLike": 0.45
      },
      "palette": [
        "ceramic.pearl",
        "metal.graphite",
        "glow.signal"
      ],
      "ownParts": 10,
      "ownRejected": 0,
      "fullyBorrowed": false,
      "bodies": 1,
      "perSlot": {
        "spine": 1,
        "neck": 1,
        "head": 1,
        "clavicleL": 1,
        "clavicleR": 1,
        "upperArmL": 1,
        "upperArmR": 1,
        "foreArmL": 1,
        "foreArmR": 1,
        "handL": 1,
        "handR": 1,
        "thighL": 1,
        "thighR": 1,
        "shinL": 1,
        "shinR": 1,
        "footL": 1,
        "footR": 1,
        "joint": 1
      },
      "anchor": true
    },
    {
      "id": "digitigrade",
      "kind": "archetype",
      "name": "鸟腿",
      "nameEn": "Digitigrade",
      "tagline": "人的手，鸟的腿",
      "taglineEn": "Human hands on animal legs",
      "plan": "rig",
      "coverage": "light",
      "base": "porcelain",
      "axes": {
        "humanLike": 0.6,
        "lifeLike": 0.6
      },
      "palette": [
        "metal.graphite",
        "matte.bone",
        "paint.hazard"
      ],
      "ownParts": 10,
      "ownRejected": 0,
      "fullyBorrowed": false,
      "bodies": 1,
      "perSlot": {
        "spine": 1,
        "neck": 1,
        "head": 1,
        "clavicleL": 1,
        "clavicleR": 1,
        "upperArmL": 1,
        "upperArmR": 1,
        "foreArmL": 1,
        "foreArmR": 1,
        "handL": 1,
        "handR": 1,
        "thighL": 1,
        "thighR": 1,
        "shinL": 1,
        "shinR": 1,
        "footL": 1,
        "footR": 1,
        "joint": 1
      },
      "anchor": true
    },
    {
      "id": "wheelleg",
      "kind": "archetype",
      "name": "轮足",
      "nameEn": "Wheelleg",
      "tagline": "它既走也滑",
      "taglineEn": "It walks and it rolls",
      "plan": "quadruped",
      "coverage": "light",
      "base": "porcelain",
      "axes": {
        "humanLike": 0.35,
        "lifeLike": 0.35
      },
      "palette": [
        "metal.graphite",
        "paint.hazard",
        "matte.ash"
      ],
      "ownParts": 1,
      "ownRejected": 1,
      "fullyBorrowed": true,
      "bodies": 262144,
      "perSlot": {
        "spine": 2,
        "neck": 2,
        "head": 2,
        "clavicleL": 2,
        "clavicleR": 2,
        "upperArmL": 2,
        "upperArmR": 2,
        "foreArmL": 2,
        "foreArmR": 2,
        "handL": 2,
        "handR": 2,
        "thighL": 2,
        "thighR": 2,
        "shinL": 2,
        "shinR": 2,
        "footL": 2,
        "footR": 2,
        "joint": 2
      },
      "anchor": true
    },
    {
      "id": "droid",
      "kind": "archetype",
      "name": "小怪物",
      "nameEn": "Droid",
      "tagline": "它不执行任务，它有性格",
      "taglineEn": "It does not perform tasks. It has a character.",
      "plan": "stub",
      "coverage": "light",
      "base": "porcelain",
      "axes": {
        "humanLike": 0.5,
        "lifeLike": 0.85
      },
      "palette": [
        "paint.hazard",
        "matte.bone",
        "metal.brass"
      ],
      "ownParts": 6,
      "ownRejected": 0,
      "fullyBorrowed": false,
      "bodies": 256,
      "perSlot": {
        "spine": 1,
        "neck": 1,
        "head": 1,
        "clavicleL": 2,
        "clavicleR": 2,
        "upperArmL": 1,
        "upperArmR": 1,
        "foreArmL": 2,
        "foreArmR": 2,
        "handL": 2,
        "handR": 2,
        "thighL": 2,
        "thighR": 2,
        "shinL": 1,
        "shinR": 1,
        "footL": 1,
        "footR": 1,
        "joint": 1
      },
      "anchor": true
    },
    {
      "id": "petbot",
      "kind": "archetype",
      "name": "宠物",
      "nameEn": "Petbot",
      "tagline": "它不像狗，但你会觉得它活着",
      "taglineEn": "Not like a dog — but you will think it is alive",
      "plan": "quadruped",
      "coverage": "light",
      "base": "porcelain",
      "axes": {
        "humanLike": 0.25,
        "lifeLike": 0.9
      },
      "palette": [
        "ceramic.pearl",
        "matte.bone",
        "glow.signal"
      ],
      "ownParts": 6,
      "ownRejected": 0,
      "fullyBorrowed": false,
      "bodies": 256,
      "perSlot": {
        "spine": 1,
        "neck": 1,
        "head": 1,
        "clavicleL": 2,
        "clavicleR": 2,
        "upperArmL": 1,
        "upperArmR": 1,
        "foreArmL": 2,
        "foreArmR": 2,
        "handL": 2,
        "handR": 2,
        "thighL": 2,
        "thighR": 2,
        "shinL": 1,
        "shinR": 1,
        "footL": 1,
        "footR": 1,
        "joint": 1
      },
      "anchor": true
    },
    {
      "id": "furball",
      "kind": "archetype",
      "name": "毛球",
      "nameEn": "Furball",
      "tagline": "它放弃了腿、手和任务",
      "taglineEn": "It gave up limbs, hands, and usefulness",
      "plan": "radial",
      "coverage": "light",
      "base": "porcelain",
      "axes": {
        "humanLike": 0.1,
        "lifeLike": 0.95
      },
      "palette": [
        "matte.bone",
        "paint.hazard",
        "ceramic.pearl"
      ],
      "ownParts": 6,
      "ownRejected": 0,
      "fullyBorrowed": false,
      "bodies": 256,
      "perSlot": {
        "spine": 1,
        "neck": 1,
        "head": 1,
        "clavicleL": 2,
        "clavicleR": 2,
        "upperArmL": 1,
        "upperArmR": 1,
        "foreArmL": 2,
        "foreArmR": 2,
        "handL": 2,
        "handR": 2,
        "thighL": 2,
        "thighR": 2,
        "shinL": 1,
        "shinR": 1,
        "footL": 1,
        "footR": 1,
        "joint": 1
      },
      "anchor": true
    },
    {
      "id": "screenface",
      "kind": "archetype",
      "name": "桌宠",
      "nameEn": "Screenface",
      "tagline": "几个自由度就够它有人格",
      "taglineEn": "A few degrees of freedom are enough for a personality",
      "plan": "column",
      "coverage": "light",
      "base": "porcelain",
      "axes": {
        "humanLike": 0.3,
        "lifeLike": 0.8
      },
      "palette": [
        "ceramic.pearl",
        "metal.graphite",
        "glow.signal"
      ],
      "ownParts": 6,
      "ownRejected": 0,
      "fullyBorrowed": false,
      "bodies": 256,
      "perSlot": {
        "spine": 1,
        "neck": 1,
        "head": 1,
        "clavicleL": 2,
        "clavicleR": 2,
        "upperArmL": 1,
        "upperArmR": 1,
        "foreArmL": 2,
        "foreArmR": 2,
        "handL": 2,
        "handR": 2,
        "thighL": 2,
        "thighR": 2,
        "shinL": 1,
        "shinR": 1,
        "footL": 1,
        "footR": 1,
        "joint": 1
      },
      "anchor": true
    },
    {
      "id": "orb",
      "kind": "archetype",
      "name": "球",
      "nameEn": "Orb",
      "tagline": "机器人为什么一定要有腿",
      "taglineEn": "Why would a robot need legs",
      "plan": "radial",
      "coverage": "light",
      "base": "porcelain",
      "axes": {
        "humanLike": 0.05,
        "lifeLike": 0.6
      },
      "palette": [
        "paint.hazard",
        "matte.bone",
        "glow.signal"
      ],
      "ownParts": 6,
      "ownRejected": 0,
      "fullyBorrowed": false,
      "bodies": 256,
      "perSlot": {
        "spine": 1,
        "neck": 1,
        "head": 1,
        "clavicleL": 2,
        "clavicleR": 2,
        "upperArmL": 1,
        "upperArmR": 1,
        "foreArmL": 2,
        "foreArmR": 2,
        "handL": 2,
        "handR": 2,
        "thighL": 2,
        "thighR": 2,
        "shinL": 1,
        "shinR": 1,
        "footL": 1,
        "footR": 1,
        "joint": 1
      },
      "anchor": true
    },
    {
      "id": "manipulator",
      "kind": "archetype",
      "name": "移动机械臂",
      "nameEn": "Manipulator",
      "tagline": "被人形热潮盖住的那个真正重要的物种",
      "taglineEn": "The species the humanoid hype buried",
      "plan": "column",
      "coverage": "light",
      "base": "porcelain",
      "axes": {
        "humanLike": 0.4,
        "lifeLike": 0.15
      },
      "palette": [
        "matte.ash",
        "metal.graphite",
        "matte.bone"
      ],
      "ownParts": 6,
      "ownRejected": 0,
      "fullyBorrowed": false,
      "bodies": 256,
      "perSlot": {
        "spine": 1,
        "neck": 1,
        "head": 1,
        "clavicleL": 2,
        "clavicleR": 2,
        "upperArmL": 1,
        "upperArmR": 1,
        "foreArmL": 2,
        "foreArmR": 2,
        "handL": 2,
        "handR": 2,
        "thighL": 2,
        "thighR": 2,
        "shinL": 1,
        "shinR": 1,
        "footL": 1,
        "footR": 1,
        "joint": 1
      },
      "anchor": true
    },
    {
      "id": "autonomous",
      "kind": "archetype",
      "name": "无人车",
      "nameEn": "Autonomous",
      "tagline": "它也是机器人，只是大了很多",
      "taglineEn": "Also a robot. Just much larger.",
      "plan": "quadruped",
      "coverage": "light",
      "base": "porcelain",
      "axes": {
        "humanLike": 0.2,
        "lifeLike": 0.25
      },
      "palette": [
        "ceramic.pearl",
        "metal.graphite",
        "glow.signal"
      ],
      "ownParts": 6,
      "ownRejected": 1,
      "fullyBorrowed": false,
      "bodies": 512,
      "perSlot": {
        "spine": 2,
        "neck": 1,
        "head": 1,
        "clavicleL": 2,
        "clavicleR": 2,
        "upperArmL": 1,
        "upperArmR": 1,
        "foreArmL": 2,
        "foreArmR": 2,
        "handL": 2,
        "handR": 2,
        "thighL": 2,
        "thighR": 2,
        "shinL": 1,
        "shinR": 1,
        "footL": 1,
        "footR": 1,
        "joint": 1
      },
      "anchor": true
    },
    {
      "id": "field",
      "kind": "archetype",
      "name": "场",
      "nameEn": "Field",
      "tagline": "身体消失，只剩运动",
      "taglineEn": "The body disappears. Only motion remains.",
      "plan": "swarm",
      "coverage": "light",
      "base": null,
      "axes": {
        "humanLike": 0.5,
        "lifeLike": 0.5
      },
      "palette": [
        "glow.signal",
        "matte.ash",
        "ceramic.pearl"
      ],
      "ownParts": 0,
      "ownRejected": 0,
      "fullyBorrowed": false,
      "bodies": null,
      "perSlot": null,
      "anchor": false
    },
    {
      "id": "guest.founder",
      "kind": "guest",
      "name": "创始人",
      "nameEn": "The Founder",
      "tagline": "（空位）把一个真实的人穿在身上",
      "taglineEn": "(vacant) Wear a real person",
      "plan": "rig",
      "coverage": "light",
      "base": "porcelain",
      "axes": {
        "humanLike": 1,
        "lifeLike": 0.9
      },
      "palette": [
        "matte.bone",
        "metal.graphite",
        "ceramic.pearl"
      ],
      "ownParts": 0,
      "ownRejected": 0,
      "fullyBorrowed": false,
      "bodies": null,
      "perSlot": null,
      "anchor": false
    },
    {
      "id": "char.dumpling",
      "kind": "character",
      "name": "团子",
      "nameEn": "Dumpling",
      "tagline": "一个软的、圆的、会喘气的东西",
      "taglineEn": "Something soft, round, and breathing",
      "plan": "mass",
      "coverage": "light",
      "base": "furball",
      "axes": {
        "humanLike": 0.3,
        "lifeLike": 0.95
      },
      "palette": [
        "matte.bone",
        "paint.hazard",
        "ceramic.pearl"
      ],
      "ownParts": 6,
      "ownRejected": 0,
      "fullyBorrowed": false,
      "bodies": 256,
      "perSlot": {
        "spine": 1,
        "neck": 1,
        "head": 1,
        "clavicleL": 2,
        "clavicleR": 2,
        "upperArmL": 1,
        "upperArmR": 1,
        "foreArmL": 2,
        "foreArmR": 2,
        "handL": 2,
        "handR": 2,
        "thighL": 2,
        "thighR": 2,
        "shinL": 1,
        "shinR": 1,
        "footL": 1,
        "footR": 1,
        "joint": 1
      },
      "anchor": true
    },
    {
      "id": "char.ghost",
      "kind": "character",
      "name": "幽灵",
      "nameEn": "Ghost",
      "tagline": "半透明的、不确定自己在不在的东西",
      "taglineEn": "Translucent, unsure whether it is here",
      "plan": "mass",
      "coverage": "light",
      "base": "coral",
      "axes": {
        "humanLike": 0.55,
        "lifeLike": 0.7
      },
      "palette": [
        "ceramic.pearl",
        "glow.signal",
        "matte.bone"
      ],
      "ownParts": 6,
      "ownRejected": 0,
      "fullyBorrowed": false,
      "bodies": 256,
      "perSlot": {
        "spine": 1,
        "neck": 1,
        "head": 1,
        "clavicleL": 2,
        "clavicleR": 2,
        "upperArmL": 1,
        "upperArmR": 1,
        "foreArmL": 2,
        "foreArmR": 2,
        "handL": 2,
        "handR": 2,
        "thighL": 2,
        "thighR": 2,
        "shinL": 1,
        "shinR": 1,
        "footL": 1,
        "footR": 1,
        "joint": 1
      },
      "anchor": true
    },
    {
      "id": "char.paper",
      "kind": "character",
      "name": "纸人",
      "nameEn": "Paper",
      "tagline": "一具折出来的身体",
      "taglineEn": "A body that was folded",
      "plan": "towering",
      "coverage": "light",
      "base": "porcelain",
      "axes": {
        "humanLike": 0.75,
        "lifeLike": 0.4
      },
      "palette": [
        "matte.bone",
        "matte.ash",
        "paint.hazard"
      ],
      "ownParts": 6,
      "ownRejected": 0,
      "fullyBorrowed": false,
      "bodies": 256,
      "perSlot": {
        "spine": 1,
        "neck": 1,
        "head": 1,
        "clavicleL": 2,
        "clavicleR": 2,
        "upperArmL": 1,
        "upperArmR": 1,
        "foreArmL": 2,
        "foreArmR": 2,
        "handL": 2,
        "handR": 2,
        "thighL": 2,
        "thighR": 2,
        "shinL": 1,
        "shinR": 1,
        "footL": 1,
        "footR": 1,
        "joint": 1
      },
      "anchor": true
    },
    {
      "id": "char.idol",
      "kind": "character",
      "name": "偶像",
      "nameEn": "Idol",
      "tagline": "一个被做成周边的你",
      "taglineEn": "You, made into merchandise",
      "plan": "rig",
      "coverage": "light",
      "base": "porcelain",
      "axes": {
        "humanLike": 0.85,
        "lifeLike": 0.6
      },
      "palette": [
        "ceramic.pearl",
        "paint.hazard",
        "glow.signal"
      ],
      "ownParts": 6,
      "ownRejected": 0,
      "fullyBorrowed": false,
      "bodies": 256,
      "perSlot": {
        "spine": 1,
        "neck": 1,
        "head": 1,
        "clavicleL": 2,
        "clavicleR": 2,
        "upperArmL": 1,
        "upperArmR": 1,
        "foreArmL": 2,
        "foreArmR": 2,
        "handL": 2,
        "handR": 2,
        "thighL": 2,
        "thighR": 2,
        "shinL": 1,
        "shinR": 1,
        "footL": 1,
        "footR": 1,
        "joint": 1
      },
      "anchor": true
    },
    {
      "id": "char.inflate",
      "kind": "character",
      "name": "充气",
      "nameEn": "Inflate",
      "tagline": "一个被气撑起来的看护者",
      "taglineEn": "A caretaker held up by air",
      "plan": "rig",
      "coverage": "light",
      "base": "porcelain",
      "axes": {
        "humanLike": 0.55,
        "lifeLike": 0.8
      },
      "palette": [
        "matte.bone",
        "ceramic.pearl",
        "matte.ash"
      ],
      "ownParts": 1,
      "ownRejected": 0,
      "fullyBorrowed": false,
      "bodies": 131072,
      "perSlot": {
        "spine": 1,
        "neck": 2,
        "head": 2,
        "clavicleL": 2,
        "clavicleR": 2,
        "upperArmL": 2,
        "upperArmR": 2,
        "foreArmL": 2,
        "foreArmR": 2,
        "handL": 2,
        "handR": 2,
        "thighL": 2,
        "thighR": 2,
        "shinL": 2,
        "shinR": 2,
        "footL": 2,
        "footR": 2,
        "joint": 2
      },
      "anchor": true
    },
    {
      "id": "char.diva",
      "kind": "character",
      "name": "歌姬",
      "nameEn": "Diva",
      "tagline": "一个被投影出来的人",
      "taglineEn": "A person made of projected light",
      "plan": "towering",
      "coverage": "light",
      "base": "char.ghost",
      "axes": {
        "humanLike": 0.8,
        "lifeLike": 0.45
      },
      "palette": [
        "glow.signal",
        "ceramic.pearl",
        "matte.ash"
      ],
      "ownParts": 0,
      "ownRejected": 0,
      "fullyBorrowed": false,
      "bodies": null,
      "perSlot": null,
      "anchor": false
    },
    {
      "id": "char.line",
      "kind": "character",
      "name": "线",
      "nameEn": "Line",
      "tagline": "一个被画出来的东西",
      "taglineEn": "Something that was drawn, not built",
      "plan": "stub",
      "coverage": "light",
      "base": "char.dumpling",
      "axes": {
        "humanLike": 0.25,
        "lifeLike": 0.9
      },
      "palette": [
        "matte.bone",
        "matte.ash",
        "paint.hazard"
      ],
      "ownParts": 6,
      "ownRejected": 1,
      "fullyBorrowed": false,
      "bodies": 256,
      "perSlot": {
        "spine": 1,
        "neck": 1,
        "head": 1,
        "clavicleL": 2,
        "clavicleR": 2,
        "upperArmL": 1,
        "upperArmR": 1,
        "foreArmL": 2,
        "foreArmR": 2,
        "handL": 2,
        "handR": 2,
        "thighL": 2,
        "thighR": 2,
        "shinL": 1,
        "shinR": 1,
        "footL": 1,
        "footR": 1,
        "joint": 1
      },
      "anchor": false
    },
    {
      "id": "guest.keynote",
      "kind": "character",
      "name": "发布会",
      "nameEn": "Keynote",
      "tagline": "舞台上的那套制服",
      "taglineEn": "The uniform worn on stage",
      "plan": "rig",
      "coverage": "light",
      "base": "porcelain",
      "axes": {
        "humanLike": 1,
        "lifeLike": 0.55
      },
      "palette": [
        "matte.ash",
        "matte.bone",
        "metal.graphite"
      ],
      "ownParts": 0,
      "ownRejected": 0,
      "fullyBorrowed": false,
      "bodies": null,
      "perSlot": null,
      "anchor": false
    },
    {
      "id": "char.tokusatsu",
      "kind": "character",
      "name": "特摄",
      "nameEn": "Tokusatsu",
      "tagline": "一件被人穿着的光",
      "taglineEn": "A light with a person inside it",
      "plan": "rig",
      "coverage": "light",
      "base": "industrial",
      "axes": {
        "humanLike": 0.95,
        "lifeLike": 0.5
      },
      "palette": [
        "metal.graphite",
        "paint.hazard",
        "glow.signal"
      ],
      "ownParts": 6,
      "ownRejected": 0,
      "fullyBorrowed": false,
      "bodies": 256,
      "perSlot": {
        "spine": 1,
        "neck": 1,
        "head": 1,
        "clavicleL": 2,
        "clavicleR": 2,
        "upperArmL": 1,
        "upperArmR": 1,
        "foreArmL": 2,
        "foreArmR": 2,
        "handL": 2,
        "handR": 2,
        "thighL": 2,
        "thighR": 2,
        "shinL": 1,
        "shinR": 1,
        "footL": 1,
        "footR": 1,
        "joint": 1
      },
      "anchor": false
    },
    {
      "id": "char.painting",
      "kind": "character",
      "name": "画",
      "nameEn": "Painting",
      "tagline": "一幅画站了起来",
      "taglineEn": "A painting that stood up",
      "plan": "rig",
      "coverage": "light",
      "base": "porcelain",
      "axes": {
        "humanLike": 1,
        "lifeLike": 0.65
      },
      "palette": [
        "matte.ash",
        "matte.bone",
        "ceramic.pearl"
      ],
      "ownParts": 6,
      "ownRejected": 0,
      "fullyBorrowed": false,
      "bodies": 256,
      "perSlot": {
        "spine": 1,
        "neck": 1,
        "head": 1,
        "clavicleL": 2,
        "clavicleR": 2,
        "upperArmL": 1,
        "upperArmR": 1,
        "foreArmL": 2,
        "foreArmR": 2,
        "handL": 2,
        "handR": 2,
        "thighL": 2,
        "thighR": 2,
        "shinL": 1,
        "shinR": 1,
        "footL": 1,
        "footR": 1,
        "joint": 1
      },
      "anchor": false
    }
  ],
  "rejects": [
    {
      "id": "foot.digitigrade.a",
      "note": "互不相连的多物体，散成几根细棍"
    },
    {
      "id": "head.char.line.a",
      "note": "金属丝格栅，配方要的是「极简圆形、无表面细节」。PBR 着色一直盖着它；描边一上就糊成一团黑 —— 描边没制造这个问题，只是掀开了它。同 head.softwear.a 一类"
    },
    {
      "id": "head.digitigrade.a",
      "note": "2-3 个互不相连的独立物体，不是单件"
    },
    {
      "id": "head.softwear.a",
      "note": "炸开的尖刺团，糊成一团（原始网格 236k 面靠焊接兜底）"
    },
    {
      "id": "joint.digitigrade.a",
      "note": "互不相连的多物体，不是关节球"
    },
    {
      "id": "joint.patrol.a",
      "note": "细长塔状不是关节球；girth 0.43 = 槽位中位数的 0.43×"
    },
    {
      "id": "shin.digitigrade.a",
      "note": "互不相连的多物体；girth 0.86 = 槽位中位数的 2.57×"
    },
    {
      "id": "spine.autonomous.a",
      "note": "三块互不相连的薄壳 + 大洞，anchor 本身就是坏的"
    },
    {
      "id": "spine.digitigrade.a",
      "note": "2-3 个互不相连的独立物体，不是单件"
    },
    {
      "id": "spine.wheelleg.a",
      "note": "碎片状薄片，girth 0.23 = spine 中位数的 0.27×，不成躯干"
    },
    {
      "id": "upperArm.digitigrade.a",
      "note": "互不相连的多物体；girth 0.98 = 槽位中位数的 3.07×"
    }
  ]
};
